### ISSUE TITLE
conda build fails on linux-anvil-comp7

### ISSUE THREAD

**Issue by awvwgk** [jhrmnn/libmbd#15]
The conda build of `libmbd` is failing using the conda-forge toolchain comp7 by crashing the host machine. Related to #13, hopefully it is more reproducible this time.

To reproduce pull the `linux-anvil-comp7` image and run (last command inside the container):

```
git clone https://github.com/jhrmnn/libmbd.git
sudo docker run -it --rm -v $PWD/libmbd:/source condaforge/linux-anvil-comp7
cd /source && conda build .conda
```

*It is highly recommended to run interactively and have a `top` instance on the host machine to monitor the memory usage and to be able kill the build job before it crashes the host machine.*

To use the conda-forge toolchain the `meta.yaml` was patched with

```patch
diff --git a/.conda/meta.yaml b/.conda/meta.yaml
index d681f4a..c2a4d0e 100644
--- a/.conda/meta.yaml
+++ b/.conda/meta.yaml
@@ -13,18 +13,20 @@ requirements:
     - python {{ python }}
     - {{ compiler('fortran') }}
     - cmake
-    - libopenblas
     - poetry
   host:
+    - libblas
+    - liblapack
     - python
     - pip
     - cffi
   run:
+    - libblas
+    - liblapack
     - python
     - cffi
     - numpy
     - scipy
-    - libopenblas
 
 test:
   requires:
```

Output from running and killing the build job: [output.txt](https://github.com/jhrmnn/libmbd/files/4924931/output.txt)
The job was started on a host machine with 32 GB of RAM and terminated as the memory usage reached 30 GB.

**Comment by jhrmnn** [comment]
Wow, this is fascinating, thanks. So it looks like it crashes when the build enters Make, but before Make reports any actual work. As if the Cmake-generated Makefile sent Make into some kind of infinite recursion. Which sounds implausible on its own, and even more when considering that the only change from my custom Conda build seems to be changing the installed libraries?!

Do I understand correctly that the quoted diff is the only difference between the crashing build and my conda build in `.conda`? Could you try if it also crashes with the original build? I'm asking because I don't use Docker, so the barrier for me reproducing this is nontrivial. Also, running make with `make VERBOSE=1` could maybe shed some light.

**Comment by jhrmnn** [comment]
Also, thanks for making the conda-forge PR, it would be great if Libmbd was available there. Also, my conda builds have just the serial version.

**Comment by awvwgk** [comment]
I'm using docker here since my OS is somewhat non-standard and also because I *might* have crashed a CI server running the very same docker image, by accident...

It halts in the dependency resolution step, for whatever reason:

```
make -C build VERBOSE=1
make: Entering directory `$SRC_DIR/build'
$BUILD_PREFIX/bin/cmake -S$SRC_DIR -B$SRC_DIR/build --check-build-system CMakeFiles/Makefile.cmake 0
$BUILD_PREFIX/bin/cmake -E cmake_progress_start $SRC_DIR/build/CMakeFiles $SRC_DIR/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory `$SRC_DIR/build'
make -f src/CMakeFiles/mbd.dir/build.make src/CMakeFiles/mbd.dir/depend
make[2]: Entering directory `$SRC_DIR/build'
cd $SRC_DIR/build && $BUILD_PREFIX/bin/cmake -E cmake_depends "Unix Makefiles" $SRC_DIR $SRC_DIR/src $SRC_DIR/build $SRC_DIR/build/src $SRC_DIR/build/src/CMakeFiles/mbd.dir/DependInfo.cmake --color=
Dependee "$SRC_DIR/build/src/CMakeFiles/mbd.dir/DependInfo.cmake" is newer than depender "$SRC_DIR/build/src/CMakeFiles/mbd.dir/depend.internal".
Dependee "$SRC_DIR/build/src/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "$SRC_DIR/build/src/CMakeFiles/mbd.dir/depend.internal".
```

Good news for you, it can be easily circumvented by not using Makefiles for the generator but something like ninja.

**Comment by jhrmnn** [comment]
Great, thanks. If that's acceptable for the conda-forge build, I'd then go with that, rather than trying to hunt this down.

**Comment by awvwgk** [comment]
You could probably crash hardware compiling dependent projects (like DFTB+) if this issue is not resolved correctly, unless you add a strict check or a sufficiently visible warning for non-Makefile generators I would say this still needs to be resolved.

**Comment by jhrmnn** [comment]
Good points. I'll try to figure it out.

**Comment by jhrmnn** [comment]
So even when everything works fine, these two lines get printed, so that's not a sign of any problem:
```
Dependee "/Users/jhermann/Code/Projects/libmbd/build/src/CMakeFiles/mbd.dir/DependInfo.cmake" is newer than depender "/Users/jhermann/Code/Projects/libmbd/build/src/CMakeFiles/mbd.dir/depend.internal".
Dependee "/Users/jhermann/Code/Projects/libmbd/build/src/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/Users/jhermann/Code/Projects/libmbd/build/src/CMakeFiles/mbd.dir/depend.internal".
```
Docker it is, I guess.

**Comment by awvwgk** [comment]
A source file including itself looks like a prominent source for infinite recursions to me:

https://github.com/jhrmnn/libmbd/blob/7964c366dc64d21d9ff4614af83bcf85e96a9bcc/src/mbd_matrix.F90#L598

This pattern will probably stress test the dependency resolution of every build system.

**Comment by jhrmnn** [comment]
Hm. Good tip. Thanks for looking into this. I haven't had an issue with this, but perhaps I've only ever used newer Cmake versions, where it doesn't cause problems. I will look into this as soon as I reproduce the issue.

Btw, I use this pattern to not having to code both real and complex versions of a function. AFAIK there is no way how to do that using standard techniques in Fortran, hence this preprocessor abuse.

**Comment by jhrmnn** [comment]
The same problem seems to have popped up when trying to add Libmbd to ESL Bundle:

https://gitlab.com/ElectronicStructureLibrary/esl-bundle/-/merge_requests/142#note_389000207

Interestingly, on one architecture Cmake timed out, on other something crashed, either Cmake or Make?

**Comment by jhrmnn** [comment]
@awvwgk Could you tell me which Cmake and Make versions are in the Docker image that Libmbd crashes?

**Comment by awvwgk** [comment]
Here you go
- CMake is 3.18.0-h5c55442_0 from conda-forge
- make is CentOS6 GNU make 3.81

Full build log included:
<details>

```
(base) [awvwgk@saw3620 libmbd]$  docker run -it --rm -v $PWD:/source condaforge/linux-anvil-comp7
[conda@2554ee2fb1c6 ~]$ cd /source
[conda@2554ee2fb1c6 source]$ conda build .conda
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from /source/.conda/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /source/.conda/conda_build_config.yaml
Attempting to finalize metadata for pymbd
INFO:conda_build.metadata:Attempting to finalize metadata for pymbd
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
BUILD START: ['pymbd-0.9.1-py36h0e1e685_0.tar.bz2']
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /opt/conda/conda-bld/pymbd_1596201813843/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho


The following NEW packages will be INSTALLED:

    _libgcc_mutex:    0.1-conda_forge            conda-forge
    _openmp_mutex:    4.5-0_gnu                  conda-forge
    ca-certificates:  2020.6.20-hecda079_0       conda-forge
    certifi:          2020.6.20-py36h9f0ad1d_0   conda-forge
    cffi:             1.14.1-py36h0ff685e_0      conda-forge
    ld_impl_linux-64: 2.34-hc38a660_9            conda-forge
    libblas:          3.8.0-17_openblas          conda-forge
    libffi:           3.2.1-he1b5a44_1007        conda-forge
    libgcc-ng:        9.3.0-h24d8f2e_11          conda-forge
    libgfortran-ng:   7.5.0-hdf63c60_11          conda-forge
    libgomp:          9.3.0-h24d8f2e_11          conda-forge
    liblapack:        3.8.0-17_openblas          conda-forge
    libopenblas:      0.3.10-pthreads_hb3c22a3_4 conda-forge
    libstdcxx-ng:     9.3.0-hdf63c60_11          conda-forge
    ncurses:          6.2-he1b5a44_1             conda-forge
    openssl:          1.1.1g-h516909a_1          conda-forge
    pip:              20.2-py_0                  conda-forge
    pycparser:        2.20-pyh9f0ad1d_2          conda-forge
    python:           3.6.11-h425cb1d_1_cpython  conda-forge
    python_abi:       3.6-1_cp36m                conda-forge
    readline:         8.0-he28a2e2_2             conda-forge
    setuptools:       49.2.0-py36h9f0ad1d_0      conda-forge
    sqlite:           3.32.3-hcee41ef_1          conda-forge
    tk:               8.6.10-hed695b0_0          conda-forge
    wheel:            0.34.2-py_1                conda-forge
    xz:               5.2.5-h516909a_1           conda-forge
    zlib:             1.2.11-h516909a_1006       conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /opt/conda/conda-bld/pymbd_1596201813843/_build_env


The following NEW packages will be INSTALLED:

    _libgcc_mutex:           0.1-conda_forge           conda-forge
    _openmp_mutex:           4.5-0_gnu                 conda-forge
    attrs:                   19.3.0-py_0               conda-forge
    binutils_impl_linux-64:  2.34-h2122c62_9           conda-forge
    binutils_linux-64:       2.34-h47ac705_23          conda-forge
    brotlipy:                0.7.0-py36h8c4c3a4_1000   conda-forge
    bzip2:                   1.0.8-h516909a_2          conda-forge
    c-ares:                  1.16.1-h516909a_0         conda-forge
    ca-certificates:         2020.6.20-hecda079_0      conda-forge
    cachecontrol:            0.12.6-py_0               conda-forge
    cachy:                   0.3.0-py_0                conda-forge
    certifi:                 2020.6.20-py36h9f0ad1d_0  conda-forge
    cffi:                    1.14.1-py36h0ff685e_0     conda-forge
    chardet:                 3.0.4-py36h9f0ad1d_1006   conda-forge
    cleo:                    0.7.6-py_0                conda-forge
    clikit:                  0.4.3-pyh9f0ad1d_0        conda-forge
    cmake:                   3.18.0-h5c55442_0         conda-forge
    cryptography:            3.0-py36h45558ae_0        conda-forge
    dbus:                    1.13.6-he372182_0         conda-forge
    entrypoints:             0.3-py36h9f0ad1d_1001     conda-forge
    expat:                   2.2.9-he1b5a44_2          conda-forge
    gcc_impl_linux-64:       7.5.0-hda68d29_11         conda-forge
    gcc_linux-64:            7.5.0-ha781d05_23         conda-forge
    gettext:                 0.19.8.1-hc5be6a0_1002    conda-forge
    gfortran_impl_linux-64:  7.5.0-h64c220c_11         conda-forge
    gfortran_linux-64:       7.5.0-ha781d05_23         conda-forge
    glib:                    2.65.0-h6f030ca_0         conda-forge
    html5lib:                1.1-pyh9f0ad1d_0          conda-forge
    idna:                    2.10-pyh9f0ad1d_0         conda-forge
    importlib-metadata:      1.1.3-py36h9f0ad1d_0      conda-forge
    importlib_metadata:      1.1.3-0                   conda-forge
    jeepney:                 0.4.3-py_0                conda-forge
    jsonschema:              3.2.0-py36h9f0ad1d_1      conda-forge
    kernel-headers_linux-64: 2.6.32-h77966d4_12        conda-forge
    keyring:                 18.0.1-py36h9f0ad1d_0     conda-forge
    krb5:                    1.17.1-hfafb76e_2         conda-forge
    ld_impl_linux-64:        2.34-hc38a660_9           conda-forge
    libcurl:                 7.71.1-hcdd3856_4         conda-forge
    libedit:                 3.1.20191231-h46ee950_1   conda-forge
    libev:                   4.33-h516909a_0           conda-forge
    libffi:                  3.2.1-he1b5a44_1007       conda-forge
    libgcc-ng:               9.3.0-h24d8f2e_11         conda-forge
    libgfortran-ng:          7.5.0-hdf63c60_11         conda-forge
    libgomp:                 9.3.0-h24d8f2e_11         conda-forge
    libiconv:                1.15-h516909a_1006        conda-forge
    libnghttp2:              1.41.0-hab1572f_1         conda-forge
    libssh2:                 1.9.0-hab1572f_5          conda-forge
    libstdcxx-ng:            9.3.0-hdf63c60_11         conda-forge
    libuv:                   1.38.0-h516909a_0         conda-forge
    lockfile:                0.12.2-py_1               conda-forge
    msgpack-python:          1.0.0-py36hdb11119_1      conda-forge
    ncurses:                 6.2-he1b5a44_1            conda-forge
    ninja:                   1.10.0-hc9558a2_0         conda-forge
    openssl:                 1.1.1g-h516909a_1         conda-forge
    pastel:                  0.2.0-py_0                conda-forge
    pcre:                    8.44-he1b5a44_0           conda-forge
    pexpect:                 4.8.0-py36h9f0ad1d_1      conda-forge
    pip:                     20.2-py_0                 conda-forge
    pkginfo:                 1.5.0.1-py_0              conda-forge
    poetry:                  1.0.9-py36h9f0ad1d_0      conda-forge
    ptyprocess:              0.6.0-py_1001             conda-forge
    pycparser:               2.20-pyh9f0ad1d_2         conda-forge
    pylev:                   1.3.0-py_0                conda-forge
    pyopenssl:               19.1.0-py_1               conda-forge
    pyparsing:               2.4.7-pyh9f0ad1d_0        conda-forge
    pyrsistent:              0.14.11-py36h8c4c3a4_1    conda-forge
    pysocks:                 1.7.1-py36h9f0ad1d_1      conda-forge
    python:                  3.6.11-h425cb1d_1_cpython conda-forge
    python_abi:              3.6-1_cp36m               conda-forge
    readline:                8.0-he28a2e2_2            conda-forge
    requests:                2.24.0-pyh9f0ad1d_0       conda-forge
    requests-toolbelt:       0.8.0-py_1                conda-forge
    rhash:                   1.3.6-h14c3975_1001       conda-forge
    secretstorage:           3.1.2-py36h9f0ad1d_1      conda-forge
    setuptools:              49.2.0-py36h9f0ad1d_0     conda-forge
    shellingham:             1.3.2-py_0                conda-forge
    six:                     1.15.0-pyh9f0ad1d_0       conda-forge
    sqlite:                  3.32.3-hcee41ef_1         conda-forge
    sysroot_linux-64:        2.12-h77966d4_12          conda-forge
    tk:                      8.6.10-hed695b0_0         conda-forge
    tomlkit:                 0.5.11-py36h9f0ad1d_1     conda-forge
    urllib3:                 1.25.10-py_0              conda-forge
    webencodings:            0.5.1-py_1                conda-forge
    wheel:                   0.34.2-py_1               conda-forge
    xz:                      5.2.5-h516909a_1          conda-forge
    zipp:                    3.1.0-py_0                conda-forge
    zlib:                    1.2.11-h516909a_1006      conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Copying /source to /opt/conda/conda-bld/pymbd_1596201813843/work/
source tree in: /opt/conda/conda-bld/pymbd_1596201813843/work
export PREFIX=/opt/conda/conda-bld/pymbd_1596201813843/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho
export BUILD_PREFIX=/opt/conda/conda-bld/pymbd_1596201813843/_build_env
export SRC_DIR=/opt/conda/conda-bld/pymbd_1596201813843/work
INFO: activate-binutils_linux-64.sh made the following environmental changes:
+ADDR2LINE=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-addr2line
+AR=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ar
+AS=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-as
-BUILD=x86_64-conda_cos6-linux-gnu
+BUILD=x86_64-conda-linux-gnu
+CXXFILT=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c++filt
+ELFEDIT=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-elfedit
+GPROF=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gprof
+HOST=x86_64-conda-linux-gnu
+LD_GOLD=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ld.gold
+LD=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ld
+NM=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-nm
+OBJCOPY=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-objcopy
+OBJDUMP=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-objdump
+RANLIB=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ranlib
+READELF=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-readelf
+SIZE=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-size
+STRINGS=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-strings
+STRIP=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-strip
INFO: activate-gcc_linux-64.sh made the following environmental changes:
+CC=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc
+CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/pymbd-0.9.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+CMAKE_PREFIX_PATH=$PREFIX:$BUILD_PREFIX/x86_64-conda-linux-gnu/sysroot/usr
+CONDA_BUILD_SYSROOT=$BUILD_PREFIX/x86_64-conda-linux-gnu/sysroot
+_CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu
+CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include
+CPP=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cpp
+DEBUG_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/pymbd-0.9.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -isystem $PREFIX/include
+GCC_AR=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ar
+GCC_NM=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-nm
+GCC=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc
+GCC_RANLIB=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ranlib
+LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib
INFO: activate-gfortran_linux-64.sh made the following environmental changes:
+DEBUG_FFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/pymbd-0.9.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments -ffunction-sections -pipe
+DEBUG_FORTRANFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/pymbd-0.9.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments -ffunction-sections -pipe
+F77=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gfortran
+F90=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gfortran
+F95=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-f95
+FC=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gfortran
+FFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/pymbd-0.9.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+FORTRANFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/pymbd-0.9.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+GFORTRAN=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gfortran

mkdir build
(cd build && cmake .. -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_LIBDIR=lib)
-- The Fortran compiler identification is GNU 7.5.0
-- The C compiler identification is GNU 7.5.0
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gfortran - skipped
-- Checking whether $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gfortran supports Fortran 90
-- Checking whether $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gfortran supports Fortran 90 - yes
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Setting build type to Debug as none was set
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - not found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - found
-- Found BLAS: $PREFIX/lib/libblas.so  
-- Looking for Fortran cheev
-- Looking for Fortran cheev - found
-- A library with LAPACK API found.
-- Configuring done
-- Generating done
-- Build files have been written to: $SRC_DIR/build
make -C build VERBOSE=1
make: Entering directory `$SRC_DIR/build'
$BUILD_PREFIX/bin/cmake -S$SRC_DIR -B$SRC_DIR/build --check-build-system CMakeFiles/Makefile.cmake 0
$BUILD_PREFIX/bin/cmake -E cmake_progress_start $SRC_DIR/build/CMakeFiles $SRC_DIR/build//CMakeFiles/progress.marks
make  -f CMakeFiles/Makefile2 all
make[1]: Entering directory `$SRC_DIR/build'
make  -f src/CMakeFiles/mbd.dir/build.make src/CMakeFiles/mbd.dir/depend
make[2]: Entering directory `$SRC_DIR/build'
cd $SRC_DIR/build && $BUILD_PREFIX/bin/cmake -E cmake_depends "Unix Makefiles" $SRC_DIR $SRC_DIR/src $SRC_DIR/build $SRC_DIR/build/src $SRC_DIR/build/src/CMakeFiles/mbd.dir/DependInfo.cmake --color=
Dependee "$SRC_DIR/build/src/CMakeFiles/mbd.dir/DependInfo.cmake" is newer than depender "$SRC_DIR/build/src/CMakeFiles/mbd.dir/depend.internal".
Dependee "$SRC_DIR/build/src/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "$SRC_DIR/build/src/CMakeFiles/mbd.dir/depend.internal".
^CTraceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 474, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 465, in execute
    verify=args.verify, variants=args.variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2864, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1995, in build
    cwd=src_dir, stats=build_stats)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 404, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 379, in _func_defaulting_env_to_os_environ
    proc = PopenWrapper(_args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 264, in __init__
    self.out, self.err = self._execute(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 329, in _execute
    time.sleep(time_int)
KeyboardInterrupt
make[2]: *** [src/CMakeFiles/mbd.dir/depend] Interrupt
make[1]: *** [src/CMakeFiles/mbd.dir/all] Interrupt
make: *** [all] Interrupt
[conda@2554ee2fb1c6 source]$ 
```
</details>

**Comment by jhrmnn** [comment]
Thanks! I can actually reproduce the error now. On MacOS at least, Docker seems to kill the process one it exceeds a memory limit. So I'll take it from here, thanks for reporting.

**Comment by jhrmnn** [comment]
The build crashes on calling `cmake -E cmake_depends`, which Stackoverflow has [this](https://stackoverflow.com/a/36734163) to say about:

> As cmake_depends is not documented in the documentation, I would call it an internal interface, that should not be used by users. If you use it, it might fail with any new version without any warning or deprecation period.

**Comment by jhrmnn** [comment]
So this definitely supports your hunch that it's the self-reference in Libmbd code.

**Comment by jhrmnn** [comment]
Yep, it's the self-reference. Now the question is why it doesn't crash on some systems and it does on other systems... Clearly this is a Cmake bug. If I could simply avoid it, I'd prefer that over using a different tool set.

**Comment by jhrmnn** [comment]
I raised an issue with Cmake's developers:

https://gitlab.kitware.com/cmake/cmake/-/issues/21044

**Comment by jhrmnn** [comment]
So Cmake actually wasn't built to handle the self-reference case, and it always enters a recursion loop. Cmake uses an internal pseudoparser that looks up `#include`'s and simply puts them on the parsing stack. But for some reason on my machine (and I assume other machine where Libmbd woorks), the infinite recursion loop is broken after 250 calls and Cmake moves on to the next file. No idea why.

But whatever the reason, this must be resolved on Libmbd's side if we want to support existing Cmake versions. Perhaps running the preprocessor explicitly as part of the build might be the easiest solution.

**Comment by jhrmnn** [comment]
Turned out the issue was that the Cmake Fortran parser doesn't understand `if <VAR> == <VALUE>`, hence the infinite recursion. After refactoring that to `ifdef/ifndef`, everything seems to work fine.

**Comment by awvwgk** [comment]
Thanks, for tracking this down. This was a major blocker for the DFTB+ integration in my opinion, I'm glad that it is finally fixed.
